# Generated by Django 4.1.3 on 2023-10-02 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.IntegerField(choices=[(1, 'mael'), (2, 'female')], default=1)),
                ('age', models.CharField(max_length=25)),
                ('education', models.IntegerField(choices=[(1, 'ปวช.'), (2, 'ปวส.'), (3, 'ปริญญาตรี'), (4, 'สูงกว่าปริญญาตรี')], default=None)),
                ('dep', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.department')),
            ],
            options={
                'verbose_name': 'Employ',
                'verbose_name_plural': 'Employs',
            },
        ),
    ]
