# Generated by Django 4.1.3 on 2023-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='sex',
            field=models.IntegerField(choices=[(1, 'ชาย'), (2, 'หญิง')], default=1),
        ),
    ]
